[default]
extend-ignore-identifiers-re = [
  "ine",
  "nam",
  "modul",
  "dentifier"
]

[default.extend-words]
hask = "hask"

[type.haskell]
extend-glob = ["*.hs"]

[type.yaml]
extend-glob = ["*.yaml"]
check-file = false
