[default]
extend-ignore-identifiers-re = [
  "ine",
  "nam",
  "modul",
  "dentifier",
  "ariable",
  "nteger",
  "efinition"
]

[default.extend-words]
hask = "hask"

[type.haskell]
extend-glob = ["*.hs"]

[type.markdown]
extend-glob = ["*.md"]

[type.yaml]
extend-glob = ["*.yaml"]
check-file = false
